# Generated by Django 3.0.4 on 2020-04-20 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_auto_20200419_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='Apply Time')),
                ('status', models.CharField(choices=[('APP', 'APPLIED'), ('WAI', 'WAITING'), ('ONG', 'ONGOING'), ('BOR', 'BORROWED'), ('OVE', 'OVERTIME'), ('CLO', 'CLOSED')], default='APP', max_length=3)),
                ('reason', models.TextField(verbose_name='Apply Reason')),
                ('reply', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Short Reply')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.Application')),
                ('title', models.CharField(max_length=150, verbose_name='Research Title')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Team Members')),
            ],
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='FacilityApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.Application')),
                ('items', models.ManyToManyField(to='inventory.Facility', verbose_name='Applied Facilities')),
            ],
            bases=('applications.application',),
        ),
    ]
