# Generated by Django 3.0.4 on 2020-05-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Apply Time')),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('APP', 'APPLIED'), ('WAI', 'WAITING'), ('ONG', 'ONGOING'), ('BOR', 'BORROWED'), ('OVE', 'OVERTIME'), ('CLO', 'CLOSED')], default='PEN', max_length=3)),
                ('reason', models.TextField(verbose_name='Apply Reason')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Staff Reply')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.Application')),
                ('title', models.CharField(max_length=150, verbose_name='Research Title')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Team Members')),
            ],
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='FacilityApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.Application')),
                ('alias', models.CharField(default='My Application', max_length=50)),
                ('items', models.ManyToManyField(to='inventory.Facility', verbose_name='Facilities Applied')),
            ],
            bases=('applications.application',),
        ),
    ]
