# Generated by Django 3.0.4 on 2020-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200423_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Apply Time'),
        ),
    ]
