# Generated by Django 3.0.4 on 2020-04-18 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=5)),
                ('school', models.CharField(choices=[('CS', 'Computer Science'), ('CE', 'Communication Engineering'), ('OE', 'OptoElectronic Engineering'), ('SE', 'Big Data and Software Engineering'), ('AUTO', 'Automation'), ('TBD', 'Unknown')], default='TBD', max_length=4)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('purchased', models.DateField()),
                ('school', models.CharField(choices=[('CS', 'Computer Science'), ('CE', 'Communication Engineering'), ('OE', 'OptoElectronic Engineering'), ('SE', 'Big Data and Software Engineering'), ('AUTO', 'Automation'), ('TBD', 'Unknown')], default='TBD', max_length=4)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
