# Generated by Django 3.0.4 on 2020-04-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200419_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='location',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
