# Generated by Django 3.0.4 on 2020-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('campus_id', models.CharField(max_length=30, unique=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('CE', 'Communication Engineering'), ('OE', 'OptoElectronic Engineering'), ('SE', 'Big Data and Software Engineering'), ('AUTO', 'Automation'), ('TBD', 'Unknown')], max_length=4, null=True)),
                ('borrow_limit', models.IntegerField(blank=True, default=1, null=True)),
                ('role', models.CharField(choices=[('VIS', 'Visitor'), ('STU', 'Student'), ('TEA', 'Teacher'), ('STA', 'Staff'), ('ADM', 'Administrator'), ('SUP', 'Superuser')], default='VIS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
