# Generated by Django 3.0.4 on 2020-04-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_delete',
            new_name='is_super',
        ),
    ]
