# Generated by Django 3.0.4 on 2020-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='borrow_limit',
        ),
        migrations.AddField(
            model_name='account',
            name='limit',
            field=models.IntegerField(default=1, verbose_name='Facility Borrow Limit'),
        ),
    ]
