# Generated by Django 3.0.4 on 2020-04-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200409_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_super',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('VIS', 'Visitor'), ('STU', 'Student'), ('TEA', 'Teacher'), ('STA', 'Staff'), ('ADM', 'Administrator'), ('SUP', 'Superuser')], default='VIS', max_length=3),
        ),
    ]
