# Generated by Django 3.0.4 on 2020-04-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200412_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='borrow_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='school',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('CE', 'Communication Engineering'), ('OE', 'OptoElectronic Engineering'), ('SE', 'Big Data and Software Engineering'), ('AUTO', 'Automation')], max_length=4, null=True),
        ),
    ]
