# Generated by Django 3.0.4 on 2020-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200412_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='borrow_limit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
