# Generated by Django 3.0.4 on 2020-04-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200412_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='school',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('CE', 'Communication Engineering'), ('OE', 'OptoElectronic Engineering'), ('SE', 'Big Data and Software Engineering'), ('AUTO', 'Automation'), ('TBD', 'Unknown')], max_length=4, null=True),
        ),
    ]
