import sqlite3

db = sqlite3.connect("../db.sqlite3")
cursor = db.cursor()


cursor.execute("delete from inventory_facility;")
cursor.execute("delete from inventory_apparatus;")
cursor.execute("delete from inventory_laboratory;")
cursor.execute("delete from bulletin_article;")
cursor.execute("delete from bulletin_facilityschedule;")


cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (1, 3, 'SE', 'AGP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (2, 2, 'AUTO', 'APM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (3, 3, 'CE', 'AT/DIN5');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (4, 3, 'AUTO', 'BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (5, 2, 'CE', 'BIOS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (6, 2, 'SE', 'BUS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (7, 3, 'SE', 'CASE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (8, 2, 'CS', 'CASE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (9, 3, 'CS', 'CD-R');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (10, 2, 'CE', 'CD-ROM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (11, 2, 'CS', 'CD-RW');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (12, 2, 'CS', 'CD-RW');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (13, 2, 'CS', 'CD-RW');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (14, 3, 'CS', 'CHASSIS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (15, 2, 'AUTO', 'CMOS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (16, 2, 'CS', 'COM PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (17, 2, 'OE', 'CPU');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (18, 3, 'AUTO', 'CPU');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (19, 2, 'CE', 'DIP SWITCHES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (20, 3, 'AUTO', 'DVD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (21, 2, 'AUTO', 'EIDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (22, 3, 'SE', 'EISA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (23, 2, 'SE', 'FLEX');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (24, 2, 'AUTO', 'FLOPPY DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (25, 3, 'CS', 'HARD DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (26, 2, 'SE', 'HEADSET');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (27, 3, 'AUTO', 'HEAT SINK');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (28, 3, 'SE', 'IDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (29, 3, 'AUTO', 'INFRARED PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (30, 2, 'SE', 'INFRARED PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (31, 3, 'AUTO', 'INTEL OVERDRIVE PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (32, 3, 'CE', 'INTEL PENTIUM PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (33, 2, 'SE', 'INTERPOSER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (34, 2, 'CE', 'IRDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (35, 2, 'CE', 'IRDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (36, 2, 'AUTO', 'IRQS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (37, 2, 'CE', 'ISA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (38, 2, 'AUTO', 'JOYSTICK');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (39, 2, 'OE', 'JUMPERS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (40, 3, 'CS', 'KEYBOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (41, 3, 'OE', 'LCD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (42, 3, 'CE', 'MCA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (43, 2, 'CS', 'MEMORY');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (44, 2, 'OE', 'MICROPHONE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (45, 2, 'OE', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (46, 2, 'SE', 'MONITOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (47, 2, 'SE', 'MOTHERBOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (48, 3, 'SE', 'MOTHERBOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (49, 3, 'OE', 'MOUSE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (50, 2, 'OE', 'NETWORK CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (51, 3, 'SE', 'NICAD BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (52, 3, 'SE', 'NIMH BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (53, 2, 'CE', 'PARALLEL PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (54, 3, 'AUTO', 'PALM PILOT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (55, 2, 'OE', 'PCI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (56, 2, 'CS', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (57, 3, 'SE', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (58, 2, 'CE', 'PDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (59, 3, 'CE', 'POWER SUPPLY');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (60, 3, 'CS', 'POWER MANAGEMENT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (61, 2, 'CS', 'POWER MANAGEMENT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (62, 2, 'CS', 'POWER MANAGEMENT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (63, 2, 'CS', 'PRINTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (64, 2, 'AUTO', 'PRINTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (65, 3, 'CE', 'PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (66, 2, 'CE', 'PS/2');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (67, 3, 'OE', 'RAID');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (68, 2, 'OE', 'RAM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (69, 3, 'SE', 'RISER BOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (70, 2, 'OE', 'SCANNER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (71, 2, 'CS', 'SCSI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (72, 2, 'CE', 'SERIAL PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (73, 3, 'CE', 'SOUND CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (74, 3, 'SE', 'SPEAKERS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (75, 3, 'SE', 'SPLITTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (76, 2, 'AUTO', 'SPS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (77, 2, 'OE', 'SURGE SUPPRESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (78, 2, 'SE', 'TAPE DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (79, 3, 'CE', 'UPS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (80, 3, 'CE', 'USB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (81, 3, 'AUTO', 'V.90');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (82, 2, 'CS', 'VIDEO CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (83, 2, 'CE', 'VLB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (84, 3, 'CS', 'WORM DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (85, 2, 'CE', 'X2');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (86, 3, 'CS', 'ZIP DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (87, 3, 'OE', 'ZIP DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (88, 3, 'CE', 'ZIP DRIVE');")


cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (1, '0JS9F7P', 296.00, '2009-05-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (2, 'BQUABV', 258.60, '2010-08-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (3, 'AW19', 24.20, '2005-02-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (4, 'HFI0692K', 142.00, '2003-05-07');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (5, 'QG43A58B8', 151.50, '2009-12-19');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (6, '3489', 21.10, '2009-03-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (7, '9ZFCT01', 126.90, '2016-04-19');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (8, 'C4399VZ', 297.90, '2019-05-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (9, '02UB1V', 221.00, '2016-12-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (10, '9ZY519OV5', 522.90, '2015-09-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (11, 'H2SE7N8', 480.60, '2002-04-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (12, '77KQLOE07', 32.00, '2002-01-22');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (13, '5JBK9O', 420.40, '2019-06-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (14, 'LQ1I02K', 376.40, '2009-05-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (15, '4J8IY', 322.80, '2017-08-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (16, '9977B8', 332.70, '2006-07-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (17, 'URVGZO22', 14.60, '2012-11-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (18, 'LA1NI2W', 214.50, '2012-01-09');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (19, 'VOG98', 539.80, '2011-09-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (20, '811J', 191.10, '2016-03-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (21, '3R8OXQ9BK', 361.60, '2015-01-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (22, 'N1NC5LE9', 541.10, '2019-07-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (23, '6TTL9', 217.20, '2011-05-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (24, 'U37F5I1U', 403.50, '2013-07-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (25, 'V958CA0', 46.60, '2003-03-09');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (26, '9MB77O', 480.30, '2000-07-22');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (27, '9JC8GZ785', 486.90, '2014-07-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (28, '3X5625K6', 236.40, '2002-11-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (29, '0181L43', 133.50, '2003-09-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (30, '25236B', 422.20, '2016-10-02');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (31, '4GB6', 321.00, '2002-09-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (32, 'O8CDZ', 512.80, '2019-05-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (33, 'GE2A', 482.00, '2006-12-22');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (34, '4FJ19', 82.40, '2006-01-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (35, '79S22', 473.40, '2003-03-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (36, 'Q4245', 306.70, '2002-01-19');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (37, '3CE95E', 359.60, '2013-09-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (38, '8Y34K', 298.90, '2004-09-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (39, '8L61LQ21S', 269.00, '2005-08-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (40, '278H6', 531.70, '2003-12-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (41, '3C38A8VN9', 545.70, '2002-03-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (42, '79I8RSRU', 485.70, '2011-09-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (43, 'XGGX', 14.80, '2013-05-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (44, '81K52', 158.40, '2015-01-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (45, 'FR3X48I', 516.40, '2007-07-27');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (46, '994Z2TX', 162.20, '2007-04-02');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (47, '92P9DPM8', 163.10, '2002-08-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (48, '5UESVX3', 443.30, '2000-10-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (49, '0YFY97', 191.20, '2005-05-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (50, 'CPQ7VAN1A', 531.70, '2017-12-02');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (51, 'AM70', 371.70, '2008-12-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (52, '4XTF004', 305.40, '2019-12-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (53, '615153', 413.20, '2000-08-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (54, 'YZLA214AS', 380.70, '2010-03-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (55, 'TGF553', 41.10, '2010-08-27');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (56, '9TV53K9', 306.60, '2008-07-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (57, 'Y15AA724', 323.20, '2011-03-02');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (58, 'E6E5', 517.20, '2007-08-01');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (59, 'D546H3B', 381.00, '2014-01-09');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (60, '48VUY992', 233.90, '2019-07-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (61, 'CL5A97IO', 550.50, '2006-02-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (62, '84F697', 236.50, '2015-07-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (63, '9M0F1Q9SQ', 129.10, '2009-06-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (64, 'EGTK1', 504.90, '2016-03-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (65, '5JB2QCN3', 373.40, '2000-03-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (66, '7A88', 213.60, '2017-12-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (67, '761JGX', 250.10, '2012-09-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (68, '0M9G06', 391.70, '2014-11-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (69, '75041ULM', 204.80, '2014-02-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (70, '37KZG', 136.50, '2010-02-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (71, 'OG3K', 5.50, '2007-01-06');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (72, 'DJH52B3', 208.90, '2003-08-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (73, 'THP2', 147.70, '2017-07-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (74, '1M432GGOZ', 292.60, '2015-08-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (75, '4U01H', 404.40, '2013-03-19');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (76, '0II85N8R', 417.30, '2000-02-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (77, '8CG3R', 224.50, '2005-11-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (78, '11T78', 543.80, '2019-05-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (79, '98JV789', 169.60, '2000-08-09');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (80, 'I3373L', 410.50, '2011-02-22');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (81, 'FXIW', 112.00, '2000-05-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (82, '46F976', 512.00, '2017-04-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (83, '6M37', 158.70, '2009-03-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (84, 'W0V76H', 329.90, '2005-09-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (85, 'N6PN11', 505.30, '2009-01-01');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (86, 'WWX3', 291.90, '2020-07-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (87, 'XJ09', 286.80, '2013-01-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (88, '1TH9', 347.20, '2018-07-07');")


cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (89, 2, 'CE', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (90, 3, 'OE', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (91, 2, 'SE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (92, 2, 'CS', 'IoT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (93, 3, 'CE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (94, 2, 'SE', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (95, 2, 'SE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (96, 3, 'CE', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (97, 2, 'CE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (98, 3, 'CS', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (99, 3, 'CE', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (100, 3, 'AUTO', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (101, 2, 'SE', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (102, 2, 'SE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (103, 3, 'OE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (104, 3, 'SE', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (105, 2, 'SE', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (106, 2, 'AUTO', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (107, 3, 'CS', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (108, 2, 'CS', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (109, 3, 'OE', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (110, 2, 'CE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (111, 3, 'CS', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (112, 3, 'SE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (113, 3, 'CS', 'Multimedia');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (114, 3, 'OE', 'Multimedia');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (115, 2, 'OE', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (116, 2, 'AUTO', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (117, 2, 'CS', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (118, 3, 'CS', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (119, 3, 'SE', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (120, 2, 'CE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (121, 2, 'CS', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (122, 2, 'SE', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (123, 2, 'SE', 'IoT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (124, 2, 'SE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (125, 3, 'SE', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (126, 3, 'CS', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (127, 2, 'AUTO', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (128, 3, 'CS', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (129, 3, 'CS', 'Multimedia');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (130, 3, 'AUTO', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (131, 2, 'SE', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (132, 2, 'OE', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (133, 2, 'AUTO', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (134, 3, 'CE', 'IoT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (135, 2, 'SE', 'Multimedia');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (136, 3, 'CE', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (137, 2, 'CS', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (138, 2, 'OE', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (139, 2, 'AUTO', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (140, 2, 'CS', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (141, 3, 'OE', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (142, 2, 'OE', 'IoT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (143, 3, 'OE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (144, 2, 'SE', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (145, 2, 'OE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (146, 3, 'OE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (147, 3, 'CE', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (148, 2, 'AUTO', 'Training Plaza');")


cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (128, 'DZ9434', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (129, 'B9535', 29);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (130, 'B4518', 13);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (131, 'A9212', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (132, 'DS4454', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (133, 'C6737', 4);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (134, 'B2147', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (135, 'A1333', 5);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (136, 'A5377', 9);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (137, 'B1749', 9);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (138, 'DS1936', 22);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (139, 'C1884', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (140, 'B1878', 21);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (141, 'DS5174', 6);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (142, 'DS7186', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (143, 'DS4645', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (144, 'DS1633', 6);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (145, 'A2353', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (146, 'DZ8854', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (147, 'C6254', 26);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (148, 'DZ8413', 8);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (89, 'C2263', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (90, 'DZ7636', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (91, 'DZ7523', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (92, 'DS4235', 23);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (93, 'B2393', 6);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (94, 'DS7585', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (95, 'A1539', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (96, 'DS5425', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (97, 'DS6899', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (98, 'C4327', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (99, 'B1892', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (100, 'DZ2843', 20);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (101, 'DS6122', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (102, 'B6715', 21);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (103, 'C7189', 6);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (104, 'B8865', 5);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (105, 'DZ5297', 25);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (106, 'A7826', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (107, 'A8555', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (108, 'A4689', 17);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (109, 'DS6383', 27);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (110, 'A2397', 16);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (111, 'A5515', 13);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (112, 'DS5241', 4);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (113, 'DS1941', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (114, 'DZ4425', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (115, 'C6725', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (116, 'B5639', 30);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (117, 'A5121', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (118, 'C4355', 10);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (119, 'DS7293', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (120, 'DS7887', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (121, 'A6182', 16);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (122, 'A3454', 27);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (123, 'DZ3162', 30);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (124, 'B5613', 8);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (125, 'B6499', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (126, 'A3345', 25);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (127, 'DS4589', 28);")


cursor.execute("insert into bulletin_article (id, published, subject, content) values (1, '2020-04-03 23:07:50.682021', 'Here is the subject for news #1', 'Here is the corresponding content for news #1  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (2, '2016-09-27 15:07:48.682049', 'Here is the subject for news #2', 'Here is the corresponding content for news #2  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (3, '2019-12-02 06:42:18.682063', 'Here is the subject for news #3', 'Here is the corresponding content for news #3  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (4, '2020-10-19 15:12:13.682076', 'Here is the subject for news #4', 'Here is the corresponding content for news #4  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (5, '2019-12-06 17:44:40.682090', 'Here is the subject for news #5', 'Here is the corresponding content for news #5  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (6, '2020-05-01 19:18:54.682109', 'Here is the subject for news #6', 'Here is the corresponding content for news #6  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (7, '2010-02-10 02:42:33.682122', 'Here is the subject for news #7', 'Here is the corresponding content for news #7  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (8, '2012-02-27 02:31:34.682134', 'Here is the subject for news #8', 'Here is the corresponding content for news #8  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (9, '2011-04-04 06:32:29.682147', 'Here is the subject for news #9', 'Here is the corresponding content for news #9  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (10, '2018-02-05 14:29:00.682161', 'Here is the subject for news #10', 'Here is the corresponding content for news #10  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (11, '2017-06-02 12:12:06.682174', 'Here is the subject for news #11', 'Here is the corresponding content for news #11  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (12, '2012-05-05 15:19:56.682186', 'Here is the subject for news #12', 'Here is the corresponding content for news #12  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (13, '2019-10-19 20:24:33.682198', 'Here is the subject for news #13', 'Here is the corresponding content for news #13  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (14, '2013-03-07 22:55:36.682210', 'Here is the subject for news #14', 'Here is the corresponding content for news #14  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (15, '2013-04-22 15:53:09.682222', 'Here is the subject for news #15', 'Here is the corresponding content for news #15  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (16, '2017-07-18 02:32:52.682234', 'Here is the subject for news #16', 'Here is the corresponding content for news #16  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (17, '2015-10-07 22:15:15.682246', 'Here is the subject for news #17', 'Here is the corresponding content for news #17  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (18, '2015-04-05 22:44:15.682282', 'Here is the subject for news #18', 'Here is the corresponding content for news #18  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (19, '2020-08-28 11:24:41.682298', 'Here is the subject for news #19', 'Here is the corresponding content for news #19  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (20, '2020-01-16 03:03:19.682311', 'Here is the subject for news #20', 'Here is the corresponding content for news #20  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (21, '2019-01-24 11:53:40.682323', 'Here is the subject for news #21', 'Here is the corresponding content for news #21  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (22, '2012-12-11 21:57:28.682336', 'Here is the subject for news #22', 'Here is the corresponding content for news #22  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (23, '2019-09-27 06:37:08.682348', 'Here is the subject for news #23', 'Here is the corresponding content for news #23  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (24, '2010-05-04 10:45:28.682360', 'Here is the subject for news #24', 'Here is the corresponding content for news #24  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (25, '2016-05-27 01:58:32.682373', 'Here is the subject for news #25', 'Here is the corresponding content for news #25  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")


cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (1, 'CS', 'DS7884', '2020-05-16', '12:26:15.682407', '18:23:51.682415');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (2, 'AUTO', 'DS8795', '2021-04-22', '12:09:50.682441', '15:54:57.682446');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (3, 'CE', 'DZ8899', '2021-03-20', '10:50:45.682470', '17:47:49.682475');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (4, 'SE', 'DZ8667', '2021-08-01', '09:12:41.682499', '17:02:46.682504');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (5, 'AUTO', 'DS9759', '2021-05-14', '08:41:30.682528', '14:54:06.682533');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (6, 'CE', 'A7738', '2020-04-23', '10:44:34.682574', '16:10:26.682580');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (7, 'AUTO', 'DS9434', '2021-03-21', '11:50:33.682604', '18:26:51.682612');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (8, 'CS', 'C7678', '2020-05-17', '12:45:37.682652', '17:15:24.682661');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (9, 'SE', 'B5845', '2021-02-06', '11:40:46.682703', '17:26:39.682715');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (10, 'CS', 'B7563', '2021-05-22', '12:06:23.682746', '14:16:34.682751');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (11, 'CE', 'A1745', '2021-07-19', '10:32:24.682775', '14:50:00.682781');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (12, 'CE', 'DS9668', '2021-09-06', '12:23:01.682805', '18:28:05.682811');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (13, 'AUTO', 'B9438', '2021-01-02', '11:44:51.682835', '14:34:24.682840');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (14, 'CE', 'DZ6992', '2020-12-26', '11:27:19.682864', '16:08:51.682870');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (15, 'OE', 'A1638', '2021-07-01', '08:36:59.682894', '18:16:05.682899');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (16, 'SE', 'C4536', '2021-09-05', '08:37:52.682923', '14:52:43.682929');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (17, 'AUTO', 'C1739', '2020-01-02', '12:57:33.682953', '18:21:50.682959');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (18, 'CS', 'DZ3699', '2020-11-28', '09:21:21.682984', '14:43:16.682990');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (19, 'CE', 'DS5913', '2021-10-27', '09:12:20.683015', '17:38:48.683022');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (20, 'OE', 'B5736', '2020-06-20', '08:02:49.683052', '16:08:06.683061');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (21, 'CS', 'DS2996', '2020-07-17', '09:20:51.683098', '18:04:59.683108');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (22, 'SE', 'A4358', '2020-12-05', '09:20:00.683148', '14:41:09.683157');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (23, 'OE', 'B5321', '2020-02-15', '09:44:09.683195', '15:15:00.683204');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (24, 'SE', 'DS8686', '2020-12-27', '10:02:25.683242', '18:01:02.683250');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (25, 'AUTO', 'B1259', '2020-02-19', '10:09:43.683294', '18:40:37.683304');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (26, 'CE', 'B4897', '2020-11-20', '12:40:01.683336', '18:13:34.683342');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (27, 'OE', 'DS7537', '2020-10-24', '10:45:35.683382', '17:06:31.683392');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (28, 'OE', 'DS5476', '2021-09-11', '10:42:00.683432', '18:56:07.683442');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (29, 'OE', 'DS4437', '2020-04-04', '09:51:01.683484', '17:00:15.683494');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (30, 'CS', 'DS1931', '2021-04-23', '10:40:59.683522', '16:13:03.683527');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (31, 'AUTO', 'B3298', '2020-01-22', '09:41:17.683549', '18:35:15.683555');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (32, 'OE', 'DZ1721', '2020-06-23', '08:14:58.683578', '15:06:33.683583');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (33, 'SE', 'DS2499', '2020-07-10', '09:57:54.683606', '14:07:56.683611');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (34, 'SE', 'DZ3169', '2021-12-01', '10:18:01.683634', '15:43:38.683639');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (35, 'OE', 'A5531', '2020-10-15', '12:47:09.683661', '18:25:04.683667');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (36, 'CS', 'A4741', '2020-09-25', '11:53:23.683733', '16:10:01.683738');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (37, 'SE', 'C9158', '2020-01-07', '12:17:06.683764', '18:57:09.683770');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (38, 'SE', 'DZ6769', '2020-04-03', '12:02:12.683795', '18:20:11.683800');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (39, 'AUTO', 'DZ4195', '2021-12-02', '09:21:03.683824', '15:47:29.683829');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (40, 'OE', 'A5694', '2020-08-13', '12:43:52.683862', '16:00:53.683872');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (41, 'SE', 'DS8747', '2021-01-13', '10:18:02.683913', '18:07:28.683923');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (42, 'SE', 'A2747', '2020-08-27', '08:20:08.683961', '17:52:56.683970');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (43, 'CS', 'C9615', '2021-12-09', '08:57:08.684009', '14:43:41.684018');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (44, 'CE', 'DZ3768', '2020-02-15', '08:37:58.684045', '16:31:21.684050');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (45, 'CS', 'B8174', '2021-12-03', '08:54:59.684073', '14:26:33.684078');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (46, 'CE', 'B9732', '2021-02-23', '12:32:39.684102', '14:29:51.684107');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (47, 'OE', 'C1414', '2020-03-20', '12:39:31.684131', '17:55:36.684136');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (48, 'CE', 'C5264', '2020-07-21', '09:13:38.684160', '15:23:42.684165');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (49, 'CS', 'DS2145', '2021-07-20', '08:24:19.684188', '16:34:09.684194');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (50, 'AUTO', 'DS2176', '2021-04-23', '08:07:22.684223', '18:24:21.684230');")


db.commit()
db.close()
