import sqlite3

db = sqlite3.connect("../db.sqlite3")
cursor = db.cursor()


cursor.execute("delete from inventory_facility;")
cursor.execute("delete from inventory_apparatus;")
cursor.execute("delete from inventory_laboratory;")


cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (1, 3, 'OE', 'AGP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (2, 2, 'CS', 'APM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (3, 3, 'CE', 'AT/DIN5');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (4, 2, 'AUTO', 'BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (5, 3, 'AUTO', 'BIOS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (6, 3, 'OE', 'BIOS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (7, 2, 'CE', 'BUS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (8, 3, 'CE', 'CASE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (9, 2, 'AUTO', 'CD-R');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (10, 3, 'CS', 'CD-ROM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (11, 2, 'OE', 'CD-RW');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (12, 2, 'SE', 'CHASSIS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (13, 3, 'CE', 'CMOS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (14, 2, 'SE', 'COM PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (15, 2, 'SE', 'CPU');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (16, 3, 'OE', 'DIP SWITCHES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (17, 2, 'CS', 'DVD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (18, 3, 'SE', 'EIDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (19, 2, 'AUTO', 'EISA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (20, 3, 'SE', 'FLEX');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (21, 3, 'CE', 'FLOPPY DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (22, 2, 'AUTO', 'FLOPPY DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (23, 3, 'OE', 'HARD DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (24, 2, 'CS', 'HARD DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (25, 3, 'SE', 'HARD DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (26, 3, 'CS', 'HEADSET');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (27, 2, 'OE', 'HEAT SINK');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (28, 2, 'CE', 'IDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (29, 3, 'AUTO', 'INFRARED PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (30, 3, 'CS', 'INTEL OVERDRIVE PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (31, 2, 'SE', 'INTEL PENTIUM PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (32, 3, 'CE', 'INTERPOSER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (33, 3, 'AUTO', 'IRDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (34, 2, 'CE', 'IRQS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (35, 2, 'AUTO', 'IRQS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (36, 3, 'CS', 'IRQS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (37, 2, 'SE', 'IRQS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (38, 2, 'CS', 'IRQS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (39, 2, 'CS', 'ISA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (40, 2, 'CE', 'JOYSTICK');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (41, 2, 'AUTO', 'JUMPERS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (42, 3, 'OE', 'KEYBOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (43, 3, 'CE', 'LCD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (44, 2, 'CE', 'MCA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (45, 2, 'CE', 'MCA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (46, 3, 'CS', 'MEMORY');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (47, 2, 'OE', 'MICROPHONE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (48, 3, 'OE', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (49, 3, 'CS', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (50, 2, 'CS', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (51, 2, 'CE', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (52, 2, 'CE', 'MONITOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (53, 2, 'CS', 'MONITOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (54, 3, 'AUTO', 'MOTHERBOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (55, 2, 'CS', 'MOUSE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (56, 3, 'CS', 'NETWORK CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (57, 3, 'CS', 'NICAD BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (58, 2, 'SE', 'NIMH BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (59, 2, 'SE', 'PARALLEL PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (60, 2, 'AUTO', 'PALM PILOT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (61, 2, 'CE', 'PCI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (62, 2, 'OE', 'PCI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (63, 2, 'AUTO', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (64, 3, 'OE', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (65, 2, 'AUTO', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (66, 2, 'SE', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (67, 2, 'SE', 'PDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (68, 3, 'OE', 'POWER SUPPLY');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (69, 3, 'CS', 'POWER MANAGEMENT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (70, 3, 'SE', 'PRINTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (71, 2, 'AUTO', 'PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (72, 3, 'CS', 'PS/2');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (73, 2, 'CE', 'RAID');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (74, 3, 'OE', 'RAID');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (75, 2, 'CS', 'RAM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (76, 2, 'CS', 'RISER BOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (77, 3, 'CE', 'SCANNER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (78, 3, 'AUTO', 'SCSI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (79, 2, 'SE', 'SERIAL PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (80, 3, 'SE', 'SERIAL PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (81, 3, 'OE', 'SOUND CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (82, 3, 'CE', 'SPEAKERS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (83, 2, 'SE', 'SPLITTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (84, 2, 'OE', 'SPS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (85, 3, 'CE', 'SURGE SUPPRESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (86, 2, 'OE', 'TAPE DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (87, 3, 'OE', 'UPS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (88, 2, 'AUTO', 'USB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (89, 2, 'OE', 'V.90');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (90, 2, 'AUTO', 'VIDEO CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (91, 2, 'AUTO', 'VLB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (92, 3, 'OE', 'VLB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (93, 2, 'AUTO', 'WORM DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (94, 3, 'CE', 'X2');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (95, 3, 'SE', 'X2');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (96, 3, 'CE', 'ZIP DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (97, 2, 'OE', 'ZIP DRIVE');")


cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (1, '1718KLH', 401.90, '2009-10-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (2, 'ROWW3Z61F', 425.60, '2017-9-7');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (3, 'LLY96DS', 213.00, '2011-6-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (4, 'JFETXMRIW', 179.60, '2020-9-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (5, 'XIK4HB', 535.80, '2012-1-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (6, 'KWLZ', 169.30, '2005-10-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (7, '6R082XATC', 365.00, '2017-7-8');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (8, '31BGF', 156.30, '2006-2-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (9, '7VH37', 335.00, '2016-7-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (10, 'D6167BV', 152.50, '2015-1-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (11, 'B16E6MZ', 284.90, '2019-7-2');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (12, 'O1851767T', 195.20, '2007-12-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (13, '1ZV70UV', 9.10, '2020-10-7');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (14, '4XZWS36CW', 69.30, '2011-9-1');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (15, 'J285', 504.60, '2008-10-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (16, '1RYUEN91W', 191.40, '2017-1-5');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (17, 'Q63G5479', 151.60, '2008-5-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (18, '96758IO0', 175.20, '2014-7-2');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (19, 'F6338T2', 506.00, '2016-10-5');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (20, 'SUHM', 482.00, '2020-1-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (21, 'F69KY85', 299.10, '2017-4-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (22, '79E3QL', 28.90, '2015-10-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (23, 'G61U0M8J3', 396.10, '2017-3-19');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (24, 'VN9E9035', 281.80, '2017-10-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (25, 'HKH0S', 276.70, '2009-12-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (26, 'J22T29', 5.40, '2018-10-19');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (27, '71G417', 105.60, '2016-11-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (28, '22UG', 429.70, '2010-11-9');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (29, 'XT995', 496.70, '2002-4-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (30, '32OMO2P', 19.60, '2012-1-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (31, 'MW66I7', 424.10, '2016-12-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (32, 'S8ALY9', 364.40, '2016-8-6');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (33, 'R66YTJ', 428.40, '2011-5-22');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (34, 'KGH9CV', 342.70, '2019-7-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (35, 'GH34', 348.50, '2008-4-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (36, 'NOO25E', 129.40, '2018-12-22');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (37, '2A8HPB', 64.50, '2006-3-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (38, '6K5X26B4M', 26.50, '2005-8-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (39, '8M59Z', 131.30, '2011-1-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (40, '83WA0E6OD', 34.60, '2006-9-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (41, 'H5NT018', 110.10, '2011-4-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (42, '2DA2R36H', 98.10, '2013-12-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (43, 'C92UR2', 541.20, '2005-11-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (44, 'ZX6MXF', 243.20, '2016-11-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (45, 'L483V380I', 206.70, '2008-5-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (46, 'A003', 115.30, '2013-10-9');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (47, 'G461', 339.30, '2005-4-18');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (48, '2G0KL85T', 335.70, '2006-5-8');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (49, 'SHQ4A8', 320.90, '2000-6-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (50, '014XK', 389.80, '2002-5-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (51, '80YQS8KI', 238.20, '2019-8-4');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (52, '83K7', 386.80, '2015-3-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (53, '5T2ZL2W4', 190.60, '2016-8-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (54, '7023UU', 415.20, '2010-3-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (55, '22PENW7', 223.20, '2000-6-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (56, 'R9DGZ9T', 79.20, '2020-11-4');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (57, '0P37EM', 328.10, '2020-10-1');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (58, '806N31Q', 317.60, '2016-7-18');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (59, 'MUNI29', 272.20, '2004-2-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (60, '8B0N', 345.70, '2017-7-2');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (61, 'CFNMT79', 55.50, '2004-5-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (62, 'P8T70', 126.00, '2007-11-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (63, 'P0HPKK9I', 95.80, '2003-9-1');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (64, 'UN7Q00C', 304.70, '2001-12-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (65, '31F3', 400.80, '2002-9-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (66, '818YB', 394.80, '2005-7-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (67, '4Q37', 478.30, '2007-6-27');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (68, '49553F', 74.30, '2000-4-27');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (69, 'I0PL1N10', 8.20, '2013-6-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (70, '64O3Y', 335.00, '2001-3-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (71, '47TDM41S', 388.30, '2011-7-18');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (72, 'T738GT52', 351.70, '2007-12-5');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (73, '45XFG0W', 499.30, '2000-3-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (74, 'W25NTT92H', 105.30, '2014-10-2');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (75, '58BJB9B7', 296.50, '2005-4-18');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (76, 'OWQ9YU', 283.60, '2018-4-4');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (77, 'XC14', 106.20, '2006-3-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (78, '3CYV3P', 468.70, '2012-9-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (79, '4H832', 42.70, '2018-6-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (80, 'W69W45ZE', 252.00, '2016-8-18');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (81, 'C06WX4P5R', 138.90, '2008-9-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (82, '7H66', 332.20, '2016-11-3');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (83, '5XZ3G1O64', 379.50, '2008-11-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (84, '49G364', 409.60, '2005-4-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (85, 'NT864CMT6', 523.40, '2020-7-4');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (86, '0X5W7X', 439.60, '2015-1-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (87, '1PODNWQ3', 513.90, '2020-9-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (88, '9Q2R', 73.10, '2006-8-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (89, 'RH50ML47', 120.60, '2002-10-6');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (90, 'VZ2Q', 11.10, '2016-10-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (91, 'IYKN4O', 129.10, '2000-7-4');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (92, '0Y13CP', 366.00, '2009-8-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (93, 'V37I', 506.70, '2004-3-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (94, '967554X', 118.40, '2002-2-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (95, '79554R', 326.00, '2001-7-3');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (96, 'HKTIFUT', 74.10, '2001-4-18');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (97, 'X28LLW9Z9', 228.70, '2017-10-22');")


cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (98, 3, 'SE', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (99, 3, 'AUTO', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (100, 3, 'CS', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (101, 3, 'OE', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (102, 2, 'OE', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (103, 3, 'SE', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (104, 3, 'AUTO', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (105, 2, 'CS', 'Multimedia');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (106, 3, 'AUTO', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (107, 3, 'OE', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (108, 2, 'CE', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (109, 2, 'AUTO', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (110, 2, 'OE', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (111, 3, 'AUTO', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (112, 3, 'AUTO', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (113, 3, 'AUTO', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (114, 3, 'AUTO', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (115, 2, 'CS', 'Multimedia');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (116, 2, 'AUTO', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (117, 3, 'CE', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (118, 2, 'SE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (119, 3, 'CS', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (120, 3, 'SE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (121, 2, 'SE', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (122, 2, 'AUTO', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (123, 3, 'AUTO', 'Multimedia');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (124, 2, 'CS', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (125, 3, 'CE', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (126, 2, 'CE', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (127, 3, 'OE', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (128, 2, 'OE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (129, 2, 'CE', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (130, 3, 'SE', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (131, 2, 'CS', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (132, 3, 'CE', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (133, 3, 'CS', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (134, 2, 'CS', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (135, 2, 'OE', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (136, 3, 'AUTO', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (137, 2, 'OE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (138, 3, 'AUTO', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (139, 2, 'OE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (140, 2, 'CE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (141, 3, 'CS', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (142, 2, 'OE', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (143, 3, 'OE', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (144, 2, 'AUTO', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (145, 3, 'AUTO', '5G/6G');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (146, 3, 'SE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (147, 3, 'OE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (148, 2, 'OE', 'IoT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (149, 3, 'CS', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (150, 3, 'OE', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (151, 3, 'OE', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (152, 2, 'CE', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (153, 3, 'SE', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (154, 2, 'AUTO', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (155, 3, 'AUTO', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (156, 2, 'AUTO', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (157, 2, 'AUTO', 'Post Quantum Cryptography');")


cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (128, 'A8433', 22);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (129, 'C3955', 16);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (130, 'B9967', 5);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (131, 'DS2598', 13);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (132, 'A5755', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (133, 'DS9756', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (134, 'C2846', 22);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (135, 'A4852', 23);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (136, 'DS3661', 22);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (137, 'B2135', 9);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (138, 'DS5198', 29);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (139, 'B8339', 26);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (140, 'C7737', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (141, 'DS8778', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (142, 'DS3574', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (143, 'DS2911', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (144, 'DS4651', 23);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (145, 'A4535', 5);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (146, 'B8637', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (147, 'B9422', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (148, 'DS7819', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (149, 'C3992', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (150, 'DS1182', 25);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (151, 'A1791', 13);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (152, 'DS7743', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (153, 'A8968', 8);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (154, 'DS4241', 10);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (155, 'A9266', 5);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (156, 'DS3196', 25);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (157, 'DZ2372', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (98, 'C8262', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (99, 'A8529', 26);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (100, 'B2763', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (101, 'C2452', 8);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (102, 'C1367', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (103, 'DS7337', 27);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (104, 'DS5632', 21);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (105, 'DS1335', 26);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (106, 'A9734', 22);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (107, 'B9218', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (108, 'B9575', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (109, 'A1282', 17);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (110, 'DS1758', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (111, 'B1679', 20);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (112, 'DS4976', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (113, 'A1618', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (114, 'DS1266', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (115, 'DS2643', 20);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (116, 'C4862', 9);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (117, 'DS7958', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (118, 'DS3822', 10);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (119, 'A8478', 10);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (120, 'C2477', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (121, 'DS6298', 10);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (122, 'A2652', 25);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (123, 'A9444', 30);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (124, 'DZ1733', 20);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (125, 'A1583', 5);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (126, 'DS9439', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (127, 'DZ6292', 23);")


db.commit()
db.close()
