import sqlite3

db = sqlite3.connect("../db.sqlite3")
cursor = db.cursor()


cursor.execute("delete from inventory_facility;")
cursor.execute("delete from inventory_apparatus;")
cursor.execute("delete from inventory_laboratory;")
cursor.execute("delete from bulletin_article;")
cursor.execute("delete from bulletin_facilityschedule;")


cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (1, 2, 'OE', 'AGP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (2, 2, 'AUTO', 'APM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (3, 3, 'SE', 'AT/DIN5');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (4, 2, 'OE', 'BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (5, 2, 'SE', 'BIOS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (6, 2, 'CE', 'BUS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (7, 2, 'CE', 'CASE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (8, 3, 'OE', 'CASE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (9, 2, 'CS', 'CASE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (10, 3, 'CS', 'CD-R');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (11, 2, 'OE', 'CD-ROM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (12, 2, 'OE', 'CD-RW');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (13, 3, 'OE', 'CHASSIS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (14, 2, 'CS', 'CMOS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (15, 3, 'AUTO', 'COM PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (16, 3, 'SE', 'CPU');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (17, 3, 'CE', 'DIP SWITCHES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (18, 2, 'CS', 'DVD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (19, 3, 'OE', 'EIDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (20, 2, 'SE', 'EIDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (21, 3, 'AUTO', 'EIDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (22, 3, 'SE', 'EISA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (23, 3, 'AUTO', 'EISA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (24, 3, 'CS', 'FLEX');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (25, 3, 'AUTO', 'FLOPPY DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (26, 3, 'OE', 'HARD DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (27, 3, 'CS', 'HEADSET');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (28, 3, 'OE', 'HEADSET');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (29, 3, 'OE', 'HEAT SINK');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (30, 3, 'CS', 'IDE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (31, 2, 'CS', 'INFRARED PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (32, 2, 'SE', 'INTEL OVERDRIVE PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (33, 2, 'CS', 'INTEL PENTIUM PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (34, 3, 'CS', 'INTERPOSER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (35, 3, 'CS', 'IRDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (36, 2, 'CE', 'IRDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (37, 3, 'CS', 'IRQS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (38, 3, 'AUTO', 'ISA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (39, 3, 'AUTO', 'JOYSTICK');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (40, 2, 'CS', 'JUMPERS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (41, 3, 'CE', 'KEYBOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (42, 2, 'CE', 'LCD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (43, 2, 'OE', 'MCA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (44, 3, 'SE', 'MEMORY');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (45, 2, 'CS', 'MICROPHONE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (46, 3, 'CE', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (47, 3, 'CE', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (48, 2, 'CE', 'MODEM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (49, 3, 'CE', 'MONITOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (50, 2, 'AUTO', 'MOTHERBOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (51, 2, 'SE', 'MOUSE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (52, 3, 'CE', 'NETWORK CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (53, 3, 'CE', 'NICAD BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (54, 3, 'CE', 'NICAD BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (55, 3, 'OE', 'NIMH BATTERIES');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (56, 3, 'CE', 'PARALLEL PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (57, 2, 'SE', 'PALM PILOT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (58, 3, 'AUTO', 'PALM PILOT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (59, 2, 'SE', 'PCI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (60, 3, 'OE', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (61, 2, 'OE', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (62, 2, 'AUTO', 'PCMCIA AND PC CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (63, 3, 'AUTO', 'PDA');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (64, 3, 'AUTO', 'POWER SUPPLY');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (65, 3, 'AUTO', 'POWER MANAGEMENT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (66, 2, 'CE', 'PRINTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (67, 3, 'CS', 'PRINTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (68, 3, 'CS', 'PROCESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (69, 2, 'SE', 'PS/2');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (70, 3, 'SE', 'RAID');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (71, 2, 'CS', 'RAM');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (72, 3, 'OE', 'RISER BOARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (73, 2, 'OE', 'SCANNER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (74, 2, 'CS', 'SCSI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (75, 3, 'AUTO', 'SERIAL PORT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (76, 3, 'SE', 'SOUND CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (77, 2, 'CS', 'SPEAKERS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (78, 2, 'AUTO', 'SPLITTER');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (79, 2, 'SE', 'SPS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (80, 3, 'CE', 'SURGE SUPPRESSOR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (81, 2, 'OE', 'TAPE DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (82, 2, 'SE', 'TAPE DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (83, 2, 'OE', 'UPS');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (84, 2, 'SE', 'USB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (85, 3, 'AUTO', 'USB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (86, 3, 'OE', 'V.90');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (87, 2, 'SE', 'VIDEO CARD');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (88, 3, 'OE', 'VLB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (89, 2, 'CE', 'VLB');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (90, 3, 'CE', 'WORM DRIVE');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (91, 3, 'AUTO', 'X2');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (92, 3, 'AUTO', 'ZIP DRIVE');")


cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (1, 'P9LK4', 338.90, '2010-03-07');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (2, '6DNU07N', 451.20, '2017-04-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (3, 'OWU24', 325.90, '2018-11-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (4, '2OX839M4', 93.10, '2020-12-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (5, '646573X', 552.60, '2017-04-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (6, 'W2V25', 37.10, '2003-06-06');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (7, '212E228NO', 465.30, '2017-08-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (8, 'SVAOV', 473.60, '2012-04-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (9, '6SJ8BC1FB', 454.00, '2001-08-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (10, 'O6XQ7O4A4', 72.30, '2009-10-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (11, 'XK1Q9', 407.80, '2005-05-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (12, 'V9H70O', 42.10, '2007-12-03');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (13, 'VT30', 290.90, '2012-07-06');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (14, '19HBM', 406.30, '2017-01-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (15, 'X4PV4', 282.90, '2014-04-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (16, 'XF74', 479.90, '2014-12-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (17, '84U0L9', 146.80, '2016-06-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (18, 'Q222UB', 330.80, '2020-04-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (19, 'U82HEDVA3', 347.70, '2012-07-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (20, 'IIFKMVK1', 355.40, '2005-06-23');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (21, '4J3YVH2H', 110.10, '2003-07-19');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (22, '5N167', 201.80, '2003-04-06');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (23, 'Z4S06', 227.70, '2008-06-09');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (24, 'TC50', 509.20, '2013-04-02');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (25, '8OGBVD', 510.00, '2004-06-05');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (26, 'GI0K7ZK', 77.60, '2012-08-03');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (27, 'OPCU4', 382.20, '2002-11-02');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (28, 'E6X063Z', 455.50, '2015-12-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (29, '6MFTK', 479.00, '2012-07-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (30, '4SA8', 297.50, '2007-04-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (31, '38038VQP6', 551.70, '2017-01-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (32, 'W58Y9HEA4', 128.60, '2013-04-16');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (33, 'V5P2', 151.20, '2003-08-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (34, '3QGUC', 45.50, '2013-01-11');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (35, '298LORR4', 282.00, '2017-12-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (36, '41IJ7H7E', 379.00, '2014-12-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (37, '7TZJKB', 15.00, '2005-02-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (38, '52Y7TMS', 155.00, '2007-12-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (39, '94784ZV8', 202.90, '2008-01-03');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (40, '9G27P823', 281.70, '2002-06-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (41, '0ZQZGT17', 27.80, '2000-05-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (42, 'ON4P5978', 507.70, '2010-05-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (43, '918U', 453.10, '2014-08-27');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (44, '9BY22', 202.90, '2010-04-14');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (45, '0VHRDI48', 15.50, '2008-12-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (46, '2LQ1T7GS', 235.40, '2001-09-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (47, 'IRI0B', 157.40, '2017-03-22');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (48, '6FP81', 461.40, '2015-09-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (49, '18120AW8', 443.10, '2020-11-03');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (50, '9O6V318', 387.70, '2015-10-07');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (51, '722085', 198.30, '2011-04-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (52, '12FF8J', 539.50, '2013-12-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (53, '3I7B7Y', 429.50, '2001-11-06');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (54, '99KP4A3', 278.60, '2014-11-07');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (55, 'RX55', 269.20, '2006-06-18');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (56, '76F6FAGRW', 193.30, '2001-01-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (57, 'VI4D7', 331.10, '2020-08-21');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (58, 'HR39ACV89', 47.20, '2017-09-26');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (59, 'O892DT65N', 218.30, '2015-08-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (60, 'VAY3Q55FW', 300.40, '2016-01-08');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (61, 'SY3D26A4', 138.60, '2003-05-20');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (62, '1J0WRUG', 135.80, '2005-02-06');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (63, '27M3', 518.90, '2016-06-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (64, 'EC63O0', 83.10, '2015-05-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (65, 'M92XP', 170.90, '2014-09-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (66, 'JML674Y18', 402.90, '2007-06-24');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (67, 'NIKFJ8IB5', 298.40, '2018-03-02');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (68, 'U6Y1477G8', 328.20, '2001-06-03');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (69, '034D2K08', 358.80, '2009-05-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (70, 'PLIV', 35.50, '2004-07-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (71, 'N5OB49K', 25.00, '2005-11-07');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (72, 'TLILF4D', 106.30, '2010-11-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (73, '7SO4U3CP', 221.70, '2018-06-17');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (74, '2WXU', 520.30, '2001-05-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (75, '05HK5WXF2', 528.60, '2014-09-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (76, '6O0Z5785B', 521.20, '2015-12-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (77, 'E9BP', 93.50, '2002-08-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (78, '22DQLN', 102.20, '2017-02-10');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (79, '6GL4AVLQ', 492.10, '2020-04-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (80, '82VEZ29', 301.40, '2018-06-06');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (81, 'L8ZWHOKA2', 548.40, '2017-07-05');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (82, '0T4CZH4', 123.80, '2009-07-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (83, 'ZX5IYIPTT', 83.80, '2009-12-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (84, '95D99', 12.60, '2002-12-12');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (85, 'HKF1R2IYD', 539.20, '2014-03-27');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (86, '3ZK11K', 470.30, '2010-01-13');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (87, '3S397', 319.00, '2007-09-25');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (88, 'F96GX', 45.30, '2016-10-04');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (89, '4I1822EY', 367.30, '2014-01-09');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (90, '38EP34H', 443.10, '2003-03-28');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (91, '3T8W40', 302.40, '2001-04-15');")
cursor.execute("insert into inventory_apparatus (facility_ptr_id, model_no, cost, purchased) values (92, '8L9EIR5', 259.60, '2015-10-12');")


cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (93, 2, 'AUTO', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (94, 3, 'CS', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (95, 2, 'AUTO', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (96, 3, 'CE', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (97, 2, 'AUTO', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (98, 2, 'SE', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (99, 3, 'CE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (100, 2, 'AUTO', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (101, 3, 'OE', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (102, 3, 'OE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (103, 3, 'SE', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (104, 2, 'CE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (105, 3, 'AUTO', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (106, 3, 'CS', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (107, 2, 'SE', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (108, 3, 'AUTO', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (109, 3, 'AUTO', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (110, 2, 'AUTO', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (111, 3, 'OE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (112, 3, 'AUTO', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (113, 2, 'SE', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (114, 3, 'CS', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (115, 3, 'OE', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (116, 3, 'OE', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (117, 2, 'SE', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (118, 3, 'OE', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (119, 2, 'OE', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (120, 2, 'SE', 'VR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (121, 3, 'CS', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (122, 2, 'CS', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (123, 3, 'CE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (124, 2, 'CS', 'Data Mining Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (125, 2, 'SE', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (126, 2, 'AUTO', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (127, 3, 'OE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (128, 2, 'SE', 'Multi-Functional Room');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (129, 2, 'AUTO', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (130, 2, 'SE', 'IoT');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (131, 3, 'SE', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (132, 2, 'CE', 'Teaching Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (133, 3, 'OE', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (134, 2, 'SE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (135, 2, 'OE', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (136, 2, 'CE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (137, 3, 'AUTO', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (138, 2, 'CE', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (139, 3, 'CS', 'Post Quantum Cryptography');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (140, 3, 'OE', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (141, 2, 'SE', 'Training Plaza');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (142, 3, 'SE', 'Cloud Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (143, 3, 'OE', 'Machine Learning');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (144, 2, 'CE', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (145, 2, 'AUTO', 'Computer Vision');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (146, 3, 'AUTO', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (147, 2, 'SE', 'AR');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (148, 2, 'OE', 'Advanced DIP');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (149, 2, 'SE', 'Linux Center');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (150, 2, 'SE', 'AI');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (151, 3, 'SE', 'Margin Computing');")
cursor.execute("insert into inventory_facility (id, staff_id, school, name) values (152, 3, 'CE', 'Training Plaza');")


cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (128, 'B5655', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (129, 'B5298', 4);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (130, 'C2147', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (131, 'B6646', 25);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (132, 'A8116', 18);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (133, 'C5883', 22);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (134, 'A6781', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (135, 'DS5482', 20);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (136, 'A6964', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (137, 'C7233', 10);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (138, 'B9824', 9);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (139, 'A5861', 23);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (140, 'B1292', 27);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (141, 'DZ8145', 13);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (142, 'DS9795', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (143, 'C6277', 27);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (144, 'B3692', 30);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (145, 'B2663', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (146, 'A4632', 29);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (147, 'DS5674', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (148, 'B7566', 5);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (149, 'DZ1827', 6);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (150, 'B9259', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (151, 'DS1595', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (152, 'B2175', 17);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (93, 'A4341', 18);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (94, 'DS1948', 12);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (95, 'DS9242', 18);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (96, 'A6699', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (97, 'DZ3942', 18);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (98, 'B9995', 27);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (99, 'DS8998', 17);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (100, 'A4578', 26);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (101, 'DS2246', 28);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (102, 'DS7488', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (103, 'B2376', 27);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (104, 'A3774', 13);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (105, 'A2647', 17);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (106, 'A8188', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (107, 'A1122', 25);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (108, 'DS3164', 29);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (109, 'DS3837', 19);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (110, 'DZ6275', 11);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (111, 'DZ8355', 4);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (112, 'A6455', 3);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (113, 'B4933', 21);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (114, 'DS1234', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (115, 'A4123', 26);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (116, 'DZ7167', 24);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (117, 'B1361', 4);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (118, 'DS8481', 8);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (119, 'DS8785', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (120, 'C5215', 18);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (121, 'DS4714', 29);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (122, 'A8619', 14);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (123, 'DZ5672', 8);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (124, 'B7973', 22);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (125, 'DS3718', 7);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (126, 'B8469', 8);")
cursor.execute("insert into inventory_laboratory (facility_ptr_id, location, capacity) values (127, 'DS8244', 6);")


cursor.execute("insert into bulletin_article (id, published, subject, content) values (1, '2013-09-20 16:39:12.730654', 'Here is the subject for news #1', 'Here is the corresponding content for news #1  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (2, '2019-03-24 05:41:09.730716', 'Here is the subject for news #2', 'Here is the corresponding content for news #2  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (3, '2019-03-08 18:59:51.730744', 'Here is the subject for news #3', 'Here is the corresponding content for news #3  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (4, '2011-02-04 04:05:42.730769', 'Here is the subject for news #4', 'Here is the corresponding content for news #4  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (5, '2014-07-08 16:47:47.730810', 'Here is the subject for news #5', 'Here is the corresponding content for news #5  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (6, '2018-11-15 01:26:29.730832', 'Here is the subject for news #6', 'Here is the corresponding content for news #6  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (7, '2017-04-07 04:14:23.730855', 'Here is the subject for news #7', 'Here is the corresponding content for news #7  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (8, '2020-05-03 11:51:32.730878', 'Here is the subject for news #8', 'Here is the corresponding content for news #8  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (9, '2019-07-23 23:28:35.730900', 'Here is the subject for news #9', 'Here is the corresponding content for news #9  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (10, '2010-08-03 21:14:32.730921', 'Here is the subject for news #10', 'Here is the corresponding content for news #10  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (11, '2017-04-02 06:10:13.730943', 'Here is the subject for news #11', 'Here is the corresponding content for news #11  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (12, '2018-11-11 23:46:02.730962', 'Here is the subject for news #12', 'Here is the corresponding content for news #12  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (13, '2011-11-04 04:44:02.730983', 'Here is the subject for news #13', 'Here is the corresponding content for news #13  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (14, '2018-09-21 17:06:29.731039', 'Here is the subject for news #14', 'Here is the corresponding content for news #14  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (15, '2010-06-10 07:02:45.731065', 'Here is the subject for news #15', 'Here is the corresponding content for news #15  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (16, '2015-07-04 00:14:40.731088', 'Here is the subject for news #16', 'Here is the corresponding content for news #16  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (17, '2017-11-05 13:00:25.731110', 'Here is the subject for news #17', 'Here is the corresponding content for news #17  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (18, '2016-08-19 13:17:58.731132', 'Here is the subject for news #18', 'Here is the corresponding content for news #18  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (19, '2014-12-13 17:51:36.731155', 'Here is the subject for news #19', 'Here is the corresponding content for news #19  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (20, '2011-10-13 10:23:11.731178', 'Here is the subject for news #20', 'Here is the corresponding content for news #20  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (21, '2019-05-05 18:53:24.731199', 'Here is the subject for news #21', 'Here is the corresponding content for news #21  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (22, '2010-03-19 22:17:02.731221', 'Here is the subject for news #22', 'Here is the corresponding content for news #22  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (23, '2013-08-10 10:33:35.731244', 'Here is the subject for news #23', 'Here is the corresponding content for news #23  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (24, '2019-06-14 08:58:17.731266', 'Here is the subject for news #24', 'Here is the corresponding content for news #24  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")
cursor.execute("insert into bulletin_article (id, published, subject, content) values (25, '2016-03-16 17:38:54.731287', 'Here is the subject for news #25', 'Here is the corresponding content for news #25  Roses are red, violets are blue. A face like yours, belongs to the zoo. ');")


cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (1, 'AUTO', 'DS1651', '2020-12-15', '09:20:25.731344', '14:05:58.731357');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (2, 'AUTO', 'DS7978', '2021-07-03', '11:01:33.731402', '16:15:59.731411');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (3, 'CE', 'C4736', '2021-07-19', '08:59:22.731453', '17:55:54.731462');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (4, 'CE', 'DS9542', '2020-11-03', '12:29:27.731505', '18:56:20.731514');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (5, 'CE', 'DS1766', '2020-10-20', '09:56:00.731557', '16:47:37.731567');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (6, 'SE', 'A7695', '2021-02-20', '11:47:00.731610', '17:20:25.731620');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (7, 'SE', 'B3685', '2020-01-20', '09:31:10.731662', '15:42:14.731672');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (8, 'SE', 'DZ4158', '2021-08-09', '11:22:50.731715', '14:30:14.731724');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (9, 'SE', 'DS5898', '2020-01-05', '12:37:19.731765', '15:43:26.731775');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (10, 'AUTO', 'DS6526', '2021-09-14', '12:45:02.731817', '14:02:44.731826');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (11, 'OE', 'DZ9569', '2021-03-19', '09:27:58.731867', '16:38:31.731876');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (12, 'CS', 'A9423', '2021-05-20', '12:48:15.731917', '16:13:32.731926');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (13, 'AUTO', 'A9549', '2020-02-07', '10:02:43.731968', '17:53:58.731977');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (14, 'CS', 'A3439', '2021-12-13', '12:40:00.732021', '18:00:16.732031');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (15, 'AUTO', 'C2686', '2020-07-20', '10:13:08.732073', '17:05:14.732083');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (16, 'CS', 'B1571', '2020-06-24', '10:15:13.732124', '14:31:23.732134');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (17, 'AUTO', 'DS3793', '2021-05-11', '08:21:37.732175', '16:32:47.732184');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (18, 'SE', 'DS8147', '2020-07-17', '08:12:25.732225', '18:53:42.732235');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (19, 'CS', 'B1637', '2021-08-14', '11:10:35.732277', '17:27:00.732286');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (20, 'OE', 'A8231', '2020-12-05', '10:40:34.732328', '18:25:37.732338');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (21, 'SE', 'DS8757', '2020-12-10', '12:32:11.732380', '17:35:58.732390');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (22, 'OE', 'DS1554', '2020-11-24', '10:14:54.732435', '14:47:23.732445');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (23, 'SE', 'A9236', '2021-06-20', '09:24:09.732485', '14:47:01.732494');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (24, 'OE', 'A6592', '2020-08-26', '11:05:11.732535', '15:27:07.732545');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (25, 'CS', 'DS1815', '2020-06-24', '11:33:06.732587', '18:39:30.732596');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (26, 'OE', 'DS5925', '2020-12-25', '08:20:58.732639', '18:55:25.732648');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (27, 'OE', 'B1422', '2021-11-19', '09:31:29.732691', '18:15:31.732701');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (28, 'CE', 'B6776', '2020-05-03', '11:51:41.732743', '16:50:59.732753');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (29, 'CE', 'DZ3965', '2020-03-15', '10:43:53.732851', '18:51:16.732862');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (30, 'AUTO', 'B6187', '2021-11-09', '08:56:04.732907', '14:41:45.732916');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (31, 'AUTO', 'C9699', '2021-09-16', '11:29:51.732960', '17:34:51.732970');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (32, 'AUTO', 'B6892', '2020-05-07', '11:48:47.733012', '17:01:48.733022');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (33, 'CE', 'A6314', '2021-07-17', '10:26:14.733064', '15:41:56.733073');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (34, 'SE', 'DZ9892', '2021-12-12', '08:29:32.733114', '14:40:59.733123');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (35, 'CS', 'A8334', '2021-04-06', '09:36:47.733161', '18:42:47.733170');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (36, 'OE', 'DS2658', '2021-02-09', '10:34:44.733210', '16:20:50.733219');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (37, 'CS', 'A8698', '2021-02-25', '08:52:46.733258', '17:08:25.733266');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (38, 'SE', 'A3746', '2020-08-19', '10:39:21.733306', '17:34:03.733315');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (39, 'AUTO', 'B7385', '2020-02-10', '09:38:32.733354', '15:39:40.733363');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (40, 'CE', 'A8737', '2021-09-20', '11:53:51.733402', '15:41:58.733412');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (41, 'OE', 'DS9765', '2021-12-12', '12:47:36.733451', '18:45:22.733459');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (42, 'AUTO', 'DS4748', '2021-03-22', '10:11:25.733497', '14:19:34.733506');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (43, 'OE', 'DS6897', '2020-05-15', '09:37:51.733546', '16:38:16.733554');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (44, 'OE', 'DS3575', '2020-12-28', '10:43:28.733592', '14:23:54.733601');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (45, 'CS', 'DS7652', '2021-11-11', '09:59:48.733641', '18:43:14.733650');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (46, 'OE', 'DS8965', '2020-12-05', '11:31:50.733692', '17:34:25.733701');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (47, 'CS', 'A9311', '2020-12-01', '11:44:50.733744', '14:59:32.733753');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (48, 'SE', 'DS4478', '2020-02-05', '09:21:50.733794', '15:24:30.733804');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (49, 'OE', 'C3482', '2020-11-08', '08:23:12.733845', '17:28:39.733855');")
cursor.execute("insert into bulletin_facilityschedule (id, school, site, day, start, end) values (50, 'AUTO', 'C4966', '2020-09-03', '10:21:38.733897', '14:33:04.733907');")


db.commit()
db.close()
